### ISSUE TITLE
Error 500: org.springframework.web.HttpSessionRequiredException: Expected session attribute &#39;ApptForm&#39;\n

### ISSUE THREAD

**Issue by mhluska** [nklayman/ca-dmv-poller#8]
I'm trying to run the following script:

```js
const Poller = require('ca-dmv-poller')

const poller = new Poller({
  itemsToProcess: 1,
  maxDistanceMiles: 15,
  zipCode: '...',
  mode: 'OfficeVisit',
  appointmentTypes: ['CID'],
  appointmentInfo: {
    firstName: 'Maros',
    lastName: 'Hluska',
    telArea: ...,
    telPrefix: ...,
    telSuffix: ...,
    birthDay: '...',
    birthMonth: '...',
    birthYear: '...',
    // dlNumber: 'I0004567', // AKA Permit Number
    // requestedTask: 'MC', // (automobile) or 'MC' (motorcycle),
    // safetyCourseCompletedSelection: 'TRUE' // or 'FALSE', motorcycle test only
  }
})

poller
  .check()
  .then(results => {
    results.forEach(result => {
      // See src/types/index.ts for all the properties of the results object
      if (result.hasFailed) {
        console.log(
          `The request to ${result.location} (id ${
            result.id
          }) failed because: ${result.cause}`
        )
        return
      }
      console.log('Day of appointment: ', result.date)
      console.log('Days until appointment: ', result.daysUntil)
      console.log('Location of appointment: ', result.location)
    })
  })
  .catch(e => console.error(e))
```

With:

```js
node poll.js
```

But I get:

```
Error: Could not connect to DMV servers
    at Poller.<anonymous> (/Users/mhluska/poll/node_modules/ca-dmv-poller/dist/index.js:177:35)
    at Generator.throw (<anonymous>)
    at rejected (/Users/mhluska/poll/node_modules/ca-dmv-poller/dist/index.js:5:65)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

Adding a console.log in the library code reveals:

```
Error 500: org.springframework.web.HttpSessionRequiredException: Expected session attribute &#39;ApptForm&#39;\n
```

Does this library work in 2019?

**Comment by prashant182** [comment]
I am getting the same error; I don't think it works in 2019.

**Comment by nklayman** [comment]
I'm pretty busy with other stuff right now, but I will fix this when I get the chance.

**Comment by jwissick** [comment]
Same error for me

**Comment by nklayman** [comment]
Unfortunately, I can't figure this one out. If someone can figure out a fix, it would be super awesome if you submitted a PR. Thanks for using the app, and hopefully it will work again someday.
